# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# source 'https://gitclub.cn/CocoaPods/Specs.git'
inhibit_all_warnings!

target 'GeBase' do

 pod 'AFNetworking'
 pod 'YYModel'
 pod 'MBProgressHUD'
 pod 'GeKit'
 pod 'FMDB'
end
