# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
source 'https://gitclub.cn/CocoaPods/Specs.git'
inhibit_all_warnings!

target 'GeBase' do

pod 'MJRefresh'
pod 'DZNEmptyDataSet'
pod 'YYModel'
pod 'MBProgressHUD'
pod 'ReactiveObjC'
#Pod 'GeKit'
end
